import { Menu, Tray, nativeImage } from 'electron';
import * as path from 'node:path';
import type { AgentSnapshot, AgentSummary, AgentState } from '../shared/types.js';

export type SimulatedState = 'idle' | 'running' | 'busy' | 'approval';
export interface TrayHandlers { onRefresh:()=>void; onToggleStartAtLogin:()=>void; onToggleDesktopLight:()=>void; onToggleMonitoring:()=>void; onOpenSettings:()=>void; onSimulate:(state:SimulatedState)=>void; onQuit:()=>void; onShowPanel:()=>void }
let tray:Tray|null=null;let blinkTimer:ReturnType<typeof setInterval>|null=null;let blinking=false;
const isApproval=(s:AgentSnapshot)=>s.state==='busy'&&!!s.detail&&/approval|permission/i.test(s.detail);
function pickIconFile(s:AgentSummary){if(s.snapshots.some(isApproval))return'tray-approval.ico';if(s.snapshots.some(x=>x.state==='busy'))return'tray-busy.ico';if(s.snapshots.some(x=>x.state==='running'))return'tray-running.ico';return'tray-idle.ico'}
function stateLabel(state:AgentState,detail?:string){const main=state==='busy'?'工作中':state==='running'?'运行中':state==='idle'?'空闲':'状态不可信';return detail?`${main} · ${detail}`:main}
function buildMenu(summary:AgentSummary,start:boolean,light:boolean,h:TrayHandlers):Electron.MenuItemConstructorOptions[]{return[{label:'打开 Agent Signal Bar',click:()=>h.onShowPanel()},{type:'separator'},{label:'刷新状态',click:()=>h.onRefresh()},{label:'登录时启动',type:'checkbox',checked:start,click:()=>h.onToggleStartAtLogin()},{label:'显示桌面信号灯',type:'checkbox',checked:light,click:()=>h.onToggleDesktopLight()},{label:'模拟状态',submenu:[{label:'空闲',click:()=>h.onSimulate('idle')},{label:'运行中',click:()=>h.onSimulate('running')},{label:'工作中',click:()=>h.onSimulate('busy')},{label:'等待授权',click:()=>h.onSimulate('approval')}]},{type:'separator'},...summary.snapshots.map(s=>({label:`${s.client==='claude'?'Claude Code':'Codex'} · ${stateLabel(s.state,s.detail)}`,enabled:false})),{type:'separator'},{label:'退出',click:()=>h.onQuit()}]}
export function createTray(resourcesDir:string,h:TrayHandlers,start:boolean,light:boolean):Tray{tray=new Tray(nativeImage.createFromPath(path.join(resourcesDir,'tray-idle.ico')));tray.setToolTip('Agent Signal Bar');tray.on('click',()=>h.onShowPanel());tray.setContextMenu(Menu.buildFromTemplate(buildMenu({snapshots:[],scannedAt:Date.now()},start,light,h)));return tray}
export function updateTray(resourcesDir:string,summary:AgentSummary,start:boolean,light:boolean,h:TrayHandlers):void{if(!tray)return;if(!blinking)tray.setImage(nativeImage.createFromPath(path.join(resourcesDir,pickIconFile(summary))));tray.setToolTip(summary.snapshots.map(s=>`${s.client==='claude'?'Claude':'Codex'}: ${s.state}`).join(' · ')||'Agent Signal Bar');tray.setContextMenu(Menu.buildFromTemplate(buildMenu(summary,start,light,h)))}
export function setTrayBlink(resourcesDir:string,blinkIcon:string|null):void{blinking=blinkIcon!==null;if(blinkIcon&&!blinkTimer){let visible=true;blinkTimer=setInterval(()=>{if(!tray)return;visible=!visible;tray.setImage(visible?nativeImage.createFromPath(path.join(resourcesDir,blinkIcon)):nativeImage.createEmpty())},500)}else if(!blinkIcon&&blinkTimer){clearInterval(blinkTimer);blinkTimer=null;tray?.setImage(nativeImage.createFromPath(path.join(resourcesDir,'tray-idle.ico')))}}
